name: Continuous Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run tests
        run: npm ci && npm test
